title: "Making Sense of the Current Campus Climate"
email: publicaffairs@ucsc.edu
description: >- # this means to ignore newlines until "baseurl:"
  What's behind the unsanctioned graduate student strike?
url: https://campus-climate.ucsc.edu
timezone: "America/Los_Angeles"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/main.jpg

include:
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
