[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.ucsc.edu; img-src 'self' *.ucsc.edu *.google.com www.google-analytics.com data:; script-src 'self' 'unsafe-inline' static.ucsc.edu *.google.com www.google-analytics.com ajax.googleapis.com *.googletagmanager.com *.fontawesome.com; style-src 'self' 'unsafe-inline' *.ucsc.edu *.google.com *.googleapis.com *.fontawesome.com unpkg.com data:; font-src 'self' fonts.gstatic.com *.fontawesome.com *.google.com; frame-src 'self' *.youtube.com; object-src 'none';"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
[[redirects]]
  from = "/campus-advisory/"
  to = "https://news.ucsc.edu/2020/02/graduate-student-strike-updates.html"
  status = 302
  force = true

