[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.ucsc.edu; img-src 'self' *.ucsc.edu data:; script-src 'self';script-src-elem 'unsafe-inline' *.netlify.com www.google-analytics.com ajax.googleapis.com *.googletagmanager.com *.fontawesome.com *.ucsc.edu; style-src 'self' 'unsafe-inline' *.ucsc.edu *.googleapis.com; font-src 'self' fonts.gstatic.com; style-src-elem data: 'self' 'unsafe-inline' fonts.googleapis.com fonts.gstatic.com unpkg.com *.fontawesome.com *.ucsc.edu;"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
[[redirects]]
  from = "/campus-advisory/"
  to = "https://news.ucsc.edu/2020/02/graduate-student-strike-updates.html"
  status = 302
  force = true

