backend:
  name: github
  repo: knice/site-campus-climate
  branch: master
publish_mode: editorial_workflow
media_folder: "assets/images" # Media files will be stored in the repo under images/uploads
collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Graduate Student Compensation'
        name: 'graduate-student-compensation'
        file: 'graduate-student-compensation.md'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Menu Order', name: 'order', widget: 'number', default: '2' }
          - { label: 'Menu Text', name: 'menu', widget: 'string' }
          - { label: 'Sidebar', name: 'sidebar', widget: 'boolean', default: true }
          - { label: 'Left Column', name: 'left_col', widget: 'boolean', default: true }
          - { label: 'Page Title', name: 'title', widget: 'string' }
          - { label: 'Meta Description', name: 'description', widget: 'text' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Living in Santa Cruz'
        name: 'living-in-santa-cruz'
        file: 'living-in-santa-cruz.md'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Menu Order', name: 'order', widget: 'number', default: '2' }
          - { label: 'Menu Text', name: 'menu', widget: 'string' }
          - { label: 'Sidebar', name: 'sidebar', widget: 'boolean', default: true }
          - { label: 'Left Column', name: 'left_col', widget: 'boolean', default: true }
          - { label: 'Page Title', name: 'title', widget: 'string' }
          - { label: 'Meta Description', name: 'description', widget: 'text' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
